### ISSUE TITLE
How to choose idle GPU for training?

### ISSUE THREAD

**Issue by Constant-TL** [huminghao16/RE3QA#15]
I used the SQuAD dataset for testing the codes. When I was preparing to train using the server's idle GPU, I found that modifying the `--local_rank 1` parameter did not work, and the following error occurred:
```
Traceback (most recent call last):
  File "/home/ltian/anaconda3/envs/RE3QA/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ltian/anaconda3/envs/RE3QA/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ltian/code/RE3QA/bert/run_squad_document_full_e2e.py", line 911, in <module>
    main()
  File "/home/ltian/code/RE3QA/bert/run_squad_document_full_e2e.py", line 752, in main
    torch.distributed.init_process_group(backend='nccl')
  File "/home/ltian/anaconda3/envs/RE3QA/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/ltian/anaconda3/envs/RE3QA/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 119, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```
Could you tell me how to choose the idle GPU when running `run_squad_document_full_e2e.py`

**Comment by Constant-TL** [comment]
When I use `--data_parallel`, it's still out of memory
