### ISSUE TITLE
build_span_corpus.py  raise ValueError()

### ISSUE THREAD

**Issue by Gabriellamin** [huminghao16/RE3QA#9]
您好，我在按照您的命令进行triviaqa-unfiltered实验时，遇到这样一个错误。
root@5df95ab01abf:/workspace/pythonprogram_zm/RE3QA/triviaqa# python build_span_corpus.py unfiltered --n_processes 1
Loading dev questions
Adding answers for dev question
Completed question 0 of 11313 (0.000)
Traceback (most recent call last):
  File "build_span_corpus.py", line 208, in <module>
    main()
  File "build_span_corpus.py", line 196, in main
    build_unfiltered_corpus(args.n_processes)
  File "build_span_corpus.py", line 154, in build_unfiltered_corpus
    FastNormalizedAnswerDetector(), n_processes)
  File "build_span_corpus.py", line 51, in build_dataset
    questions = compute_answer_spans_par(questions, corpus, tokenizer, answer_detector, n_process)
  File "/workspace/pythonprogram_zm/RE3QA/triviaqa/answer_detection.py", line 95, in compute_answer_spans_par
    compute_answer_spans(questions, corpus, tokenizer, detector)
  File "/workspace/pythonprogram_zm/RE3QA/triviaqa/answer_detection.py", line 73, in compute_answer_spans
    raise ValueError()
ValueError
经过debug调试，我发现了这样一个问题。在dev的第140个问题时，当进行到all_docs的第三个doc时，经过file_id_map映射得到的文件为
/data/triviaqa/evidence/Wikipedia/jacqueline_du_pre.txt
该文件不存在，所以返回为None.因此报了上图的错误。
查看数据集所在文件夹，发现该doc所对应的文件为，
/data/triviaqa/evidence/Wikipedia/jacqueline_du_ pré.txt
可见，是file_id_map在存储这个映射时出了错误。我觉得可能是编码的问题。但是我不懂，为什么会出现这个问题呢？请问该如何解决呢？

**Comment by huminghao16** [comment]
请参考https://github.com/huminghao16/RE3QA/issues/6#issuecomment-524787384
估计是系统默认编码的问题

**Comment by Gabriellamin** [comment]
我把系统默认编码改成了作者说的'en_US.UTF-8',该报错依然存在
